name: SE333_CI
on:
  push:
    branches:
      - main

jobs:
  SE333_CI_JOB:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4

      - name: setupJava
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64

      - name: Run Checkstyle
        run: mvn -B checkstyle:checkstyle

      - name: Upload Checkstyle Result
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-result
          path: target/checkstyle-result.xml

      - name: Run Maven Test
        run: mvn -B test

      - name: Jacoco Report
        run: mvn -B jacoco:report

      - name: Upload Jacoco Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/